// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_SySK4LXYdKC5BiIYL1bur7HWnO3NwNk',
    appId: '1:386296777771:web:ca62be1c33a8f63b3fae6e',
    messagingSenderId: '386296777771',
    projectId: 'integration-testing-a20ff',
    authDomain: 'integration-testing-a20ff.firebaseapp.com',
    storageBucket: 'integration-testing-a20ff.firebasestorage.app',
    measurementId: 'G-ML5ZVSJ9DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK0AQXEZDQQhqb5by11bdMxV_Y6RxP378',
    appId: '1:386296777771:android:2e7499f33439b20d3fae6e',
    messagingSenderId: '386296777771',
    projectId: 'integration-testing-a20ff',
    storageBucket: 'integration-testing-a20ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAatRqfz0LhessXow_ZUHijmDbtok4wWsk',
    appId: '1:386296777771:ios:ffa9ecb1d805ca733fae6e',
    messagingSenderId: '386296777771',
    projectId: 'integration-testing-a20ff',
    storageBucket: 'integration-testing-a20ff.firebasestorage.app',
    iosBundleId: 'com.example.integrationTesting',
  );
}
